[package]

name = "libraries"
version = "0.0.1"
authors = ["katand <katandps@gmail.com>"]

[[bin]]
name = "factorial"
path = "factorial.rs"

[[bin]]
name = "permutation"
path = "permutation.rs"

[[bin]]
name = "combination"
path = "combination.rs"
